import type { Metadata } from "next"
import { Geist_Mono } from "next/font/google"
import { ViewTransitions } from "next-view-transitions"
import "./globals.css"
import QueryProvider from "@/components/query-provider"

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${geistMono.className} antialiased min-h-screen`}>
          <QueryProvider>{children}</QueryProvider>
        </body>
      </html>
    </ViewTransitions>
  )
}
